// packages/solid/src/index.ts
import { createSignal, createMemo, onCleanup } from "solid-js";
import { constrain, merge, without, toObject, fromURL } from "@jpahd/qparams";
import type { Schema } from "@jpahd/qparams";

type ParamsInput = URLSearchParams | string | Record<string, string>;

const CHANGE_EVENT = "qparams:change";

function pushURL(search: string): void {
  const url = new URL(window.location.href);
  url.search = search;
  window.history.pushState({}, "", url);
  window.dispatchEvent(new Event(CHANGE_EVENT));
}

export function createQParams(schema: Schema) {
  const [search, setSearch] = createSignal(
    typeof window !== "undefined" ? window.location.search : "",
  );

  const onChange = () => setSearch(window.location.search);
  window.addEventListener("popstate", onChange);
  window.addEventListener(CHANGE_EVENT, onChange);
  onCleanup(() => {
    window.removeEventListener("popstate", onChange);
    window.removeEventListener(CHANGE_EVENT, onChange);
  });

  const params = createMemo(() => constrain(schema, search()));

  function update(incoming: ParamsInput): void {
    const next = merge(schema, fromURL(window.location.href), incoming);
    pushURL(next.toString());
  }

  function strip(options: { static?: boolean; forbidden?: boolean } = {}): URLSearchParams {
    return without(schema, params(), options);
  }

  return {
    params,
    update,
    strip,
    toObject: () => toObject(params()),
  };
}

// packages/react/src/index.ts
import { useSyncExternalStore, useCallback, useMemo } from "react";
import { constrain, merge, without, toObject, fromURL } from "@jpahd/qparams";
import type { Schema } from "@jpahd/qparams";

type ParamsInput = URLSearchParams | string | Record<string, string>;

const CHANGE_EVENT = "qparams:change";

function pushURL(search: string): void {
  const url = new URL(window.location.href);
  url.search = search;
  window.history.pushState({}, "", url);
  window.dispatchEvent(new Event(CHANGE_EVENT));
}

function subscribe(cb: () => void): () => void {
  window.addEventListener("popstate", cb);
  window.addEventListener(CHANGE_EVENT, cb);
  return () => {
    window.removeEventListener("popstate", cb);
    window.removeEventListener(CHANGE_EVENT, cb);
  };
}

function getSnapshot(): string {
  return window.location.search;
}

function getServerSnapshot(): string {
  return "";
}

export function useQParams(schema: Schema) {
  const search = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
  const params = useMemo(() => constrain(schema, search), [schema, search]);

  const update = useCallback(
    (incoming: ParamsInput) => {
      const next = merge(schema, fromURL(window.location.href), incoming);
      pushURL(next.toString());
    },
    [schema],
  );

  const strip = useCallback(
    (options: { static?: boolean; forbidden?: boolean } = {}) => {
      return without(schema, params, options);
    },
    [schema, params],
  );

  return {
    params,
    update,
    strip,
    toObject: () => toObject(params),
  };
}
